//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.06 at 04:38:08 PM IST 
//

package in.gov.uidai.authentication.uid_auth_request._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import in.gov.uidai.authentication.common.types._1.Meta;

@XmlRootElement(name = "Auth", namespace = "http://www.uidai.gov.in/authentication/uid-auth-request/2.0")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Auth", propOrder = { "uses", "meta", "skey", "data", "hmac" })
public class Auth {

	@XmlElement(name = "Uses", required = true)
	protected Uses uses;

	@XmlElement(name = "Meta", required = true)
	protected Meta meta;

	@XmlElement(name = "Skey", required = true)
	protected Skey skey;

	@XmlElement(name = "Data", required = true)
	protected Data data;

	@XmlElement(name = "Hmac", required = true)
	protected byte[] hmac;

	@XmlAttribute(name = "uid", required = true)
	protected String uid;

	@XmlAttribute(name = "rc", required = false)
	protected RcFlag rc;

	@XmlAttribute(name = "ac", required = true)
	protected String ac;

	@XmlAttribute(name = "tid", required = true)
	protected String tid;

	@XmlAttribute(name = "ver")
	protected String ver;

	@XmlAttribute(name = "txn", required = true)
	protected String txn;

	@XmlAttribute(name = "lk", required = true)
	protected String lk;

	@XmlAttribute(name = "sa", required = true)
	protected String sa;

	public Uses getUses() {
		return this.uses;
	}

	public void setUses(Uses value) {
		this.uses = value;
	}

	public Meta getMeta() {
		return this.meta;
	}

	public void setMeta(Meta value) {
		this.meta = value;
	}

	public Skey getSkey() {
		return this.skey;
	}

	public void setSkey(Skey value) {
		this.skey = value;
	}

	public Data getData() {
		return this.data;
	}

	public void setData(Data value) {
		this.data = value;
	}

	public byte[] getHmac() {
		return this.hmac;
	}

	public void setHmac(byte[] value) {
		this.hmac = value;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String value) {
		this.uid = value;
	}

	public String getAc() {
		return this.ac;
	}

	public void setAc(String value) {
		this.ac = value;
	}

	public String getTid() {
		return this.tid;
	}

	public void setTid(String value) {
		this.tid = value;
	}

	public String getVer() {
		return this.ver;
	}

	public void setVer(String value) {
		this.ver = value;
	}

	public String getTxn() {
		return this.txn;
	}

	public void setTxn(String value) {
		this.txn = value;
	}

	public String getLk() {
		return this.lk;
	}

	public void setLk(String value) {
		this.lk = value;
	}

	public String getSa() {
		return this.sa;
	}

	public void setSa(String value) {
		this.sa = value;
	}

	public RcFlag getRc() {
		return this.rc;
	}

	public void setRc(RcFlag rc) {
		this.rc = rc;
	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "value" })
	public static class Data {

		@XmlValue
		protected byte[] value;

		@XmlAttribute(name = "type")
		protected DataType type;

		public byte[] getValue() {
			return this.value;
		}

		public void setValue(byte[] value) {
			this.value = value;
		}

		public DataType getType() {
			if (this.type == null)
				return DataType.X;
			return this.type;
		}

		public void setType(DataType value) {
			this.type = value;
		}
	}

}