//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.06 at 04:38:08 PM IST 
//

package in.gov.uidai.authentication.uid_auth_request._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Uses")
public class Uses {

	@XmlAttribute(name = "pi", required = true)
	protected UsesFlag pi;

	@XmlAttribute(name = "pa", required = true)
	protected UsesFlag pa;

	@XmlAttribute(name = "pfa", required = true)
	protected UsesFlag pfa;

	@XmlAttribute(name = "bio", required = true)
	protected UsesFlag bio;

	@XmlAttribute(name = "bt")
	protected String bt;

	@XmlAttribute(name = "pin", required = true)
	protected UsesFlag pin;

	@XmlAttribute(name = "otp", required = true)
	protected UsesFlag otp;

	public UsesFlag getPi() {
		return this.pi;
	}

	public void setPi(UsesFlag value) {
		this.pi = value;
	}

	public UsesFlag getPa() {
		return this.pa;
	}

	public void setPa(UsesFlag value) {
		this.pa = value;
	}

	public UsesFlag getPfa() {
		return this.pfa;
	}

	public void setPfa(UsesFlag value) {
		this.pfa = value;
	}

	public UsesFlag getBio() {
		return this.bio;
	}

	public void setBio(UsesFlag value) {
		this.bio = value;
	}

	public String getBt() {
		return this.bt;
	}

	public void setBt(String value) {
		this.bt = value;
	}

	public UsesFlag getPin() {
		return this.pin;
	}

	public void setPin(UsesFlag value) {
		this.pin = value;
	}

	public UsesFlag getOtp() {
		return this.otp;
	}

	public void setOtp(UsesFlag value) {
		this.otp = value;
	}
}