//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.06 at 04:38:08 PM IST 
//

package in.gov.uidai.authentication.otp._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(namespace = "", name = "OtpRes")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtpRes")
public class OtpRes {

	@XmlAttribute(name = "txn")
	protected String txn;

	@XmlAttribute(name = "err")
	protected String err;

	@XmlAttribute(name = "code")
	protected String code;

	@XmlAttribute(name = "ts")
	protected String ts;

	@XmlAttribute(name = "info")
	protected String info;

	@XmlAttribute(name = "ret")
	protected OtpResult ret;

	public String getTxn() {
		return this.txn;
	}

	public void setTxn(String value) {
		this.txn = value;
	}

	public String getErr() {
		return this.err;
	}

	public void setErr(String value) {
		this.err = value;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String value) {
		this.code = value;
	}

	public String getTs() {
		return this.ts;
	}

	public void setTs(String value) {
		this.ts = value;
	}

	public OtpResult getRet() {
		return this.ret;
	}

	public void setRet(OtpResult value) {
		this.ret = value;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}
}